name: diff_image2
description: A package to get the difference between two images. Currently supports fetching images from web and from local memory.
version: 1.0.2
homepage: https://github.com/suyie001/diff_image2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.4
  image: ^3.1.3
#  meta: ^1.7.0
#  path: ^1.6.0


